baseURL = 'https://blog.simplytracktime.com/'
languageCode = 'en-us'
title = "Simply Track Time"
theme = 'hugo-theme-cleanwhite'
preserveTaxonomyNames = true

[pagination]
  pagerSize = 5

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "img/river.png"
  site_logo = "img/logo.jpg"
  avatar = "img/logo.jpg"
  description = "Investigating ways to achieve the best return on time invested."
  upstreamAttribution = true
  last_posts = true

